import os
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

class DatabaseClient:
    """
    Person 2's Domain:
    Handles all interactions with the provided ZwickRoell MongoDB container.
    """
    def __init__(self):
        # The user will define MONGO_URI in their local .env file.
        uri = os.getenv("MONGO_URI", "mongodb://localhost:27017")
        self.client = AsyncIOMotorClient(uri)
        # ZwickRoell's database is typically structured with Tests and Values collections.
        self.db = self.client.get_database("zwickroell")
        self.tests_coll = self.db.get_collection("Tests")
        self.values_coll = self.db.get_collection("Values")

    async def execute_raw_aggregation(self, pipeline: list) -> list:
        """
        Executes a raw MongoDB aggregation pipeline generated by Person 3's LLM.
        This runs against the Tests collection by default.
        """
        try:
            cursor = self.tests_coll.aggregate(pipeline)
            results = await cursor.to_list(length=1000)  # Capping to avoid memory crashes
            return results
        except Exception as e:
            # Propagate the error up so Person 3's LLM auto-correction loop can fix it.
            raise ValueError(f"MongoDB Execution Error: {str(e)}")

    async def get_test_metadata(self, test_id: str):
        """
        Helper method to fetch raw details for a specific test document by ID.
        """
        return await self.tests_coll.find_one({"_id": test_id})
